@php
    $pages = array('manage-stickers',
        'manage-gifts',
        'add-new-gift',
        'add-new-sticker',
        'manage-photos',
        'general-settings',
        'dashboard',
        'site-settings',
        'dashboard',
        'site-features',
        'amazon-settings',
        'email-settings',
        'social-login',
        'chat-settings',
        'manage-languages',
        'add-language',
        'edit-lang',
        'manage-users',
        'manage-payments',
        'manage-profile-fields',
        'add-new-profile-field',
        'edit-profile-field',
        'manage-verification-reqeusts',
        'payment-reqeuests',
        'affiliates-settings',
        'referrals-list',
        'pro-memebers',
        'pro-settings',
        'payments',
        'payment-settings',
        'manage-pages',
        'manage-groups',
        'manage-posts',
        'manage-articles',
        'manage-events',
        'manage-forum-sections',
        'manage-forum-forums',
        'manage-forum-threads',
        'manage-forum-messages',
        'create-new-section',
        'create-new-forum',
        'manage-movies',
        'add-new-movies',
        'manage-games',
        'add-new-game',
        'ads-settings',
        'manage-site-ads',
        'manage-user-ads',
        'manage-site-design',
        'manage-announcements',
        'mailing-list',
        'mass-notifications',
        'ban-users',
        'generate-sitemap',
        'manage-invitation-keys',
        'backups',
        'manage-custom-pages',
        'add-new-custom-page',
        'edit-custom-page',
        'edit-terms-pages',
        'manage-reports',
        'push-notifications-system',
        'manage-api-access-keys',
        'verfiy-applications',
        'manage-updates',
        'changelog',
        'online-users',
        'custom-code',
        'manage-third-psites',
        'edit-movie',
        'auto-delete',
        'manage-themes',
        'change-site-desgin',
        'custom-design',
        'fake-users',
        'manage-announcements',
        'manage-genders',
        'add-genders',
        'edit-genders',
        'bank-receipts',
        'video-settings',
        'manage-website-ads',

        'manage-success-stories',
        'add-success-stories',
        'edit-success-stories',

        'add-new-article',
        'edit-new-article',
        'manage-blog-categories',
        'edit-article',
        'edit-blog-category',

        //'manage-user-verification',
        'push-notifications-system',
        'edit-user-permissions',

        'affiliates-settings',
        'payment-requests',
        'referrals-list',
        'mock-email',

        'pages-seo',

        'manage-countries',
        'add-countries',
        'edit-countries',

        'manage-verification-requests',
        'live',
        'manage-invitation',
        'manage-apps',
        'auto-like',
        'manage-faqs',
        'manage-currencies',
        'manage_terms_pages',
        'manage_emails',
        'system_status',
    );
@endphp

<div class="navigation">
    <div class="navigation-header">
        <span>Navigation</span>
        <a href="#">
            <i class="ti-close"></i>
        </a>
    </div>
    <div class="navigation-menu-body">
    </div>

</div>